
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "esdmelfzeszjtbnoajig"
organization_id = "1"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL to access Supabase Studio from the browser. Set this when using with tooling like Ngrok.
# api_url = "https://api.supabase.example.com"

# Email testing server. Not required for production.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000", "http://localhost"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Number of seconds to refresh an authentication session.
tls_enforcement = "none"
# The default security mode to use when persisting a session to the browser.
same_site_value = "lax"

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending OTP to users
template = "Your code is {{.Code}}"

# Use pre-defined map of phone number to OTP for testing
[auth.sms.test_otp]
# 4152127777 = "123456"

# Configure one of the supported SMS providers: twilio, messagebird, textlocal, vonage
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
# DO NOT commit your Twilio auth token to git. Use environment variable substitution instead:
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

# Use custom SMTP server for sending emails. Falls back to the built-in SMTP server if disabled.
[auth.smtp]
enabled = false
sender_name = ""
sender_address = ""
host = ""
port = 25
username = ""
# DO NOT commit your SMTP password to git. Use environment variable substitution instead:
password = "env(SUPABASE_AUTH_SMTP_PASSWORD)"
# Uncomment if emails sent from local development should have their links automatically updated
# to use your Studio URL. You can also add a custom database connection string to migrate across projects.
# database_url = "postgres://postgres:postgres@127.0.0.1:54322/postgres"
# studio_url = "http://127.0.0.1:54323"
# Uncomment if you want to force TLS connections to the SMTP server.
# tls_without_checkserver_identity = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: postgres, bigquery, snowflake
backend = "postgres"
# opentelemetry_endpoint = ""

# Configure analytics for postgres.
[analytics.postgres]
# Enable drop_analytics_schema_on_delete to drop the analytics schema when you run supabase stop.
# Enabled by default for smaller development data volumes. Disable if you'd like to persist long-term analytics data.
drop_analytics_schema_on_delete = true
# Set host to "localhost" when developing with cli, default is 127.0.0.1.
host = "127.0.0.1"

[experimental.seo.ssr]
# Flag to enable/disable SSR.
disabled = true
# V8 JavaScript engine native binary.
v8_native = ""
# Edge Function's serving directory.
serving_dir = ""
# URL base path where assets are resolved relative to.
base_path = ""
# Unused, remove after API deprecation.
dist = ""
# Temp directory.
temp_dir = ""
# Entrypoint.
handler = ""

[edge_functions]
enabled = true
port = 54321
public_functions_enabled = true

[functions.smart-venue-assistant]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false
