
project_id = "esdmelfzeszjtbnoajig"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325

[storage]
enabled = true

[auth]
enabled = true

[auth.external.apple]
enabled = false

[auth.external.github]
enabled = false

[auth.external.gitlab]
enabled = false

[auth.external.google]
enabled = false

[auth.external.twitter]
enabled = false

[auth.external.keycloak]
enabled = false

[auth.external.linkedin]
enabled = false

[auth.external.workos]
enabled = false

[auth.external.bitbucket]
enabled = false

[auth.external.discord]
enabled = false

[auth.external.azure]
enabled = false

[functions]
[functions.send-booking-invite]
verify_jwt = false

[functions.send-invitation-response]
verify_jwt = false

[vector]
enabled = false
